# This file outlines the applications that should
# be changed when themeswap.py is run.

alacritty:
  config: ~/.config/alacritty/alacritty.yml
  commands: 

polybar:
  config: ~/.config/polybar/colors
  commands: ~/.config/polybar/startpolybar.sh

vscode:
  config: ~/.config/Code/User/settings.json
  commands:

gtk:
  config: ~/.config/xsettingsd/xsettingsd.conf
  commands: killall -HUP xsettingsd

wallpaper:
  config: ~/.config/wallpaper
  commands: feh --bg-fill ~/.config/wallpaper
